"""initial schema

Revision ID: e45a955730a0
Revises: 
Create Date: 2026-09-26 13:29:05.150351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e45a955730a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ENUMS = (
    "question_kind", "content_status", "answer_content_type", "media_kind",
    "media_processing_status", "debate_side", "rep_reason", "report_target", "report_reason",
    "report_status", "ban_scope", "appeal_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('legal_pages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('requires_consent', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_pages')),
    sa.UniqueConstraint('slug', name=op.f('uq_legal_pages_slug'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=False),
    sa.Column('reputation', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('level', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('streak_days', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('streak_last_date', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('followee_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name=op.f('ck_follows_no_self_follow')),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], name=op.f('fk_follows_followee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id', name=op.f('pk_follows'))
    )
    op.create_table('legal_page_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name=op.f('fk_legal_page_versions_edited_by_users')),
    sa.ForeignKeyConstraint(['page_id'], ['legal_pages.id'], name=op.f('fk_legal_page_versions_page_id_legal_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_page_versions')),
    sa.UniqueConstraint('page_id', 'version', name='uq_legal_version')
    )
    op.create_table('mod_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_mod_actions_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mod_actions'))
    )
    op.create_index('ix_mod_actions_actor', 'mod_actions', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.Enum('question', 'answer', 'user', name='report_target'), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'bullying', 'nsfw', 'doxxing', 'self_harm', 'illegal', 'other', name='report_reason'), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'rejected', name='report_status'), server_default='open', nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_reports_assigned_to_users')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_reports_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('reporter_id', 'target_type', 'target_id', name='uq_reports_once')
    )
    op.create_index('ix_reports_queue', 'reports', ['status', sa.literal_column('priority DESC'), 'created_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('rooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('is_official', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('member_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_rooms_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('slug', name=op.f('uq_rooms_slug'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('user_consents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('page_slug', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_consents'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_user_roles_granted_by_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('bans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_by', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.Enum('global', 'room', name='ban_scope'), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_by', sa.BigInteger(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appeal_status', sa.Enum('none', 'pending', 'accepted', 'rejected', name='appeal_status'), server_default='none', nullable=False),
    sa.Column('appeal_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_bans_issued_by_users')),
    sa.ForeignKeyConstraint(['lifted_by'], ['users.id'], name=op.f('fk_bans_lifted_by_users')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_bans_report_id_reports')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_bans_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bans'))
    )
    op.create_index('ix_bans_user_active', 'bans', ['user_id', 'ends_at'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('opinion', 'knowledge', 'story', 'debate', name='question_kind'), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('debate_side_a', sa.String(length=80), nullable=True),
    sa.Column('debate_side_b', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden', 'deleted', 'pending', 'processing', name='content_status'), server_default='active', nullable=False),
    sa.Column('best_answer_id', sa.BigInteger(), nullable=True),
    sa.Column('score_hot', sa.Float(), server_default='0', nullable=False),
    sa.Column('answers_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('views_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind <> 'debate' OR (debate_side_a IS NOT NULL AND debate_side_b IS NOT NULL)", name=op.f('ck_questions_debate_sides')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_questions_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_questions_category_id_categories')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_questions_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index('ix_questions_author_created', 'questions', ['author_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_questions_fts', 'questions', [sa.literal_column("to_tsvector('russian', title || ' ' || coalesce(body, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_questions_room_hot', 'questions', ['room_id', sa.literal_column('score_hot DESC')], unique=False)
    op.create_table('room_members',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_members_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_members'))
    )
    op.create_table('answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'voice', 'video', name='answer_content_type'), server_default='text', nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('debate_side', sa.Enum('a', 'b', name='debate_side'), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden', 'deleted', 'pending', 'processing', name='content_status'), server_default='active', nullable=False),
    sa.Column('score', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type = 'text' AND body IS NOT NULL AND length(body) BETWEEN 1 AND 5000", name=op.f('ck_answers_text_only_mvp')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_answers_author_id_users')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    op.create_index(op.f('ix_answers_author_id'), 'answers', ['author_id'], unique=False)
    op.create_index('ix_answers_question_score', 'answers', ['question_id', sa.literal_column('score DESC')], unique=False)
    op.create_table('debate_votes',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.Enum('a', 'b', name='debate_side'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_debate_votes_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_debate_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'user_id', name=op.f('pk_debate_votes'))
    )
    op.create_table('answer_media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('answer_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('voice', 'video', name='media_kind'), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('waveform', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('uploaded', 'transcoding', 'ready', 'failed', name='media_processing_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms > 0 AND duration_ms <= 60000', name=op.f('ck_answer_media_duration')),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answer_media_answer_id_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_media')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answer_media_answer_id'))
    )
    op.create_table('reputation_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('author_vote', 'upvote', 'downvote', 'vote_revoked', 'mod_penalty', name='rep_reason'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('answer_id', sa.BigInteger(), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_reputation_events_actor_id_users')),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_reputation_events_answer_id_answers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_reputation_events_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_reputation_events_question_id_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_reputation_events_room_id_rooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reputation_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reputation_events'))
    )
    op.create_index('ix_rep_user_created', 'reputation_events', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('votes',
    sa.Column('answer_id', sa.BigInteger(), nullable=False),
    sa.Column('voter_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('is_author_vote', sa.Boolean(), nullable=False),
    sa.Column('counted', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_author_vote AND value IN (5, -1)) OR (NOT is_author_vote AND value IN (1, -1))', name=op.f('ck_votes_value_rule')),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_votes_answer_id_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], name=op.f('fk_votes_voter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id', 'voter_id', name=op.f('pk_votes'))
    )
    # ### end Alembic commands ###
    # --- ручные дополнения ---
    # Циклическая FK questions.best_answer_id → answers.id (use_alter): добавляем после обеих таблиц.
    op.create_foreign_key(op.f('fk_questions_best_answer_id_answers'), 'questions', 'answers',
                          ['best_answer_id'], ['id'], ondelete='SET NULL')
    # Лог модерации: только добавление записей.
    op.execute("""
        CREATE FUNCTION mod_actions_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'mod_actions is append-only';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER mod_actions_no_update_delete
        BEFORE UPDATE OR DELETE ON mod_actions
        FOR EACH ROW EXECUTE FUNCTION mod_actions_append_only();
    """)



def downgrade() -> None:
    op.drop_constraint(op.f('fk_questions_best_answer_id_answers'), 'questions', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_index('ix_rep_user_created', table_name='reputation_events')
    op.drop_table('reputation_events')
    op.drop_table('answer_media')
    op.drop_table('debate_votes')
    op.drop_index('ix_answers_question_score', table_name='answers')
    op.drop_index(op.f('ix_answers_author_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_table('room_members')
    op.drop_index('ix_questions_room_hot', table_name='questions')
    op.drop_index('ix_questions_fts', table_name='questions', postgresql_using='gin')
    op.drop_index('ix_questions_author_created', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_bans_user_active', table_name='bans')
    op.drop_table('bans')
    op.drop_table('user_roles')
    op.drop_table('user_consents')
    op.drop_table('settings')
    op.drop_table('rooms')
    op.drop_table('role_permissions')
    op.drop_index('ix_reports_queue', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_mod_actions_actor', table_name='mod_actions')
    op.drop_table('mod_actions')
    op.drop_table('legal_page_versions')
    op.drop_table('follows')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('legal_pages')
    op.drop_table('categories')
    # ### end Alembic commands ###
    # --- ручные дополнения ---
    op.execute("DROP FUNCTION IF EXISTS mod_actions_append_only()")
    for enum_name in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

