"""badges and ban appeals

Revision ID: aee38286dfc6
Revises: e45a955730a0
Create Date: 2026-09-26 13:38:09.688658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aee38286dfc6'
down_revision: Union[str, None] = 'e45a955730a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badges',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_badges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'code', name=op.f('pk_user_badges'))
    )
    op.add_column('bans', sa.Column('appeal_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bans', sa.Column('appeal_resolved_by', sa.BigInteger(), nullable=True))
    op.add_column('bans', sa.Column('appeal_resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bans', sa.Column('appeal_comment', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_bans_appeal_resolved_by_users'), 'bans', 'users', ['appeal_resolved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bans_appeal_resolved_by_users'), 'bans', type_='foreignkey')
    op.drop_column('bans', 'appeal_comment')
    op.drop_column('bans', 'appeal_resolved_at')
    op.drop_column('bans', 'appeal_resolved_by')
    op.drop_column('bans', 'appeal_created_at')
    op.drop_table('user_badges')
    # ### end Alembic commands ###
