"""notifications, streak freeze, edited_at

Revision ID: 6bde81f6aaed
Revises: aee38286dfc6
Create Date: 2026-09-26 18:39:18.127202
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6bde81f6aaed'
down_revision: Union[str, None] = 'aee38286dfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user', 'notifications', ['user_id', 'is_read', sa.literal_column('id DESC')], unique=False)
    op.add_column('answers', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('questions', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('streak_freeze_week', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streak_freeze_week')
    op.drop_column('questions', 'edited_at')
    op.drop_column('answers', 'edited_at')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
