"""kombucha mini-game

Revision ID: 0007_kombucha
Revises: 0006_profile_faq
Create Date: 2026-09-27 16:38:45.184447
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0007_kombucha'
down_revision: Union[str, None] = '0006_profile_faq'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kombuchas',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('best_xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('generation', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('sweet', sa.Double(), nullable=False),
    sa.Column('tea', sa.Double(), nullable=False),
    sa.Column('clean', sa.Double(), nullable=False),
    sa.Column('happy', sa.Double(), nullable=False),
    sa.Column('alive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('zero_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldowns', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('born_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('died_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kombuchas_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_kombuchas'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kombuchas')
    # ### end Alembic commands ###
