"""kombucha market trades freeze wall

Revision ID: 0009_kb_market_wall
Revises: 0008_wood_kombucha
Create Date: 2026-09-27 17:48:00.577397
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0009_kb_market_wall'
down_revision: Union[str, None] = '0008_wood_kombucha'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutation_counters',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('issued', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_mutation_counters'))
    )
    op.create_table('wall_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_wall_posts_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_wall_posts_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wall_posts'))
    )
    op.create_index('ix_wall_posts_owner', 'wall_posts', ['owner_id', sa.literal_column('id DESC')], unique=False)
    op.create_table('kombucha_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('give_id', sa.BigInteger(), nullable=False),
    sa.Column('want_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_kombucha_trades_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['give_id'], ['kombuchas.id'], name=op.f('fk_kombucha_trades_give_id_kombuchas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_kombucha_trades_to_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['want_id'], ['kombuchas.id'], name=op.f('fk_kombucha_trades_want_id_kombuchas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kombucha_trades'))
    )
    op.create_index('ix_kombucha_trades_from', 'kombucha_trades', ['from_user_id', 'status'], unique=False)
    op.create_index('ix_kombucha_trades_to', 'kombucha_trades', ['to_user_id', 'status'], unique=False)
    op.add_column('kombuchas', sa.Column('frozen', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('kombuchas', sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('kombuchas', sa.Column('price', sa.BigInteger(), nullable=True))
    op.add_column('kombuchas', sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # номера экземпляров для уже выпавших мутаций (по порядку выпадения) + счётчики
    import json
    conn = op.get_bind()
    counters: dict[str, int] = {}
    rows = conn.execute(sa.text("SELECT id, mutations FROM kombuchas WHERE mutations <> '[]'::jsonb ORDER BY id")).all()
    for kid, muts in rows:
        changed = False
        for m in sorted(muts, key=lambda x: x.get("at") or ""):
            if not m.get("serial"):
                counters[m["code"]] = counters.get(m["code"], 0) + 1
                m["serial"] = counters[m["code"]]
                changed = True
        if changed:
            conn.execute(sa.text("UPDATE kombuchas SET mutations = CAST(:m AS jsonb) WHERE id = :id"),
                         {"m": json.dumps(muts, ensure_ascii=False), "id": kid})
    for code, n in counters.items():
        conn.execute(sa.text("INSERT INTO mutation_counters (code, issued) VALUES (:c, :n)"), {"c": code, "n": n})


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kombuchas', 'listed_at')
    op.drop_column('kombuchas', 'price')
    op.drop_column('kombuchas', 'frozen_at')
    op.drop_column('kombuchas', 'frozen')
    op.drop_index('ix_kombucha_trades_to', table_name='kombucha_trades')
    op.drop_index('ix_kombucha_trades_from', table_name='kombucha_trades')
    op.drop_table('kombucha_trades')
    op.drop_index('ix_wall_posts_owner', table_name='wall_posts')
    op.drop_table('wall_posts')
    op.drop_table('mutation_counters')
    # ### end Alembic commands ###
