"""tasks, mold, weekly sprouts, provenance

Revision ID: 0010_tasks_hardcore
Revises: 0009_kb_market_wall
Create Date: 2026-09-27 18:34:19.674811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0010_tasks_hardcore'
down_revision: Union[str, None] = '0009_kb_market_wall'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('proof', sa.String(length=300), server_default='', nullable=False),
    sa.Column('reward', sa.BigInteger(), nullable=False),
    sa.Column('slots', sa.BigInteger(), nullable=False),
    sa.Column('slots_left', sa.BigInteger(), nullable=False),
    sa.Column('fee', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refunded', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_tasks_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_author', 'tasks', ['author_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status', sa.literal_column('id DESC')], unique=False)
    op.create_table('task_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_submissions_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_submissions')),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_submission_user')
    )
    op.create_index('ix_task_submissions_status', 'task_submissions', ['status', 'created_at'], unique=False)
    op.add_column('kombucha_trades', sa.Column('message', sa.String(length=140), nullable=True))
    op.add_column('kombuchas', sa.Column('mold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('kombuchas', sa.Column('last_sprout_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('kombuchas', sa.Column('sprout_count', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('kombuchas', sa.Column('talk_count', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('kombuchas', sa.Column('owners', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # уже делившиеся грибы: считаем, что деление было при последнем уходе, — следующее через неделю
    op.execute("UPDATE kombuchas SET sprout_count = 1, last_sprout_at = updated_at, care_days = 0 WHERE sprouted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kombuchas', 'owners')
    op.drop_column('kombuchas', 'talk_count')
    op.drop_column('kombuchas', 'sprout_count')
    op.drop_column('kombuchas', 'last_sprout_at')
    op.drop_column('kombuchas', 'mold')
    op.drop_column('kombucha_trades', 'message')
    op.drop_index('ix_task_submissions_status', table_name='task_submissions')
    op.drop_table('task_submissions')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_author', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
