"""Клубы и Гриб-Танк: кооперативы, общие банки, лиги, войны, лента.

Revision ID: 23e158677256
Revises: 0017_halloween_admin_close
Create Date: 2026-10-06 17:32:31.604169
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0018_clubs'
down_revision: Union[str, None] = '0017_halloween_admin_close'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_leagues',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.BigInteger(), nullable=False),
    sa.Column('size', sa.BigInteger(), server_default='50', nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_club_leagues'))
    )
    op.create_table('clubs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('tag', sa.String(length=5), nullable=False),
    sa.Column('emblem', sa.String(length=16), server_default='🍄', nullable=False),
    sa.Column('color', sa.String(length=9), server_default='#ff5a36', nullable=False),
    sa.Column('color2', sa.String(length=9), server_default='#ff8a3d', nullable=False),
    sa.Column('description', sa.String(length=280), server_default='', nullable=False),
    sa.Column('join_mode', sa.String(length=8), server_default='open', nullable=False),
    sa.Column('min_level', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('members', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('capacity', sa.BigInteger(), server_default='5', nullable=False),
    sa.Column('level', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('account', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('perks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='active', nullable=False),
    sa.Column('week_key', sa.String(length=8), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disbanded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disband_reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], name=op.f('fk_clubs_leader_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_index('ix_clubs_active', 'clubs', ['status', sa.literal_column('last_active_at DESC')], unique=False)
    op.create_index(op.f('ix_clubs_leader_id'), 'clubs', ['leader_id'], unique=False)
    op.create_index(op.f('ix_clubs_status'), 'clubs', ['status'], unique=False)
    op.create_index('uq_clubs_name_lower', 'clubs', [sa.literal_column('lower(name)')], unique=True)
    op.create_index('uq_clubs_tag_lower', 'clubs', [sa.literal_column('lower(tag)')], unique=True)
    op.create_table('club_bank_tx',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_bank_tx_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_bank_tx_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_bank_tx'))
    )
    op.create_index('ix_club_bank_tx_club', 'club_bank_tx', ['club_id', sa.literal_column('id DESC')], unique=False)
    op.create_index('uq_club_bank_tx_ref', 'club_bank_tx', ['club_id', 'reason', 'ref'], unique=True)
    op.create_table('club_banned_users',
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('by_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=140), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['by_id'], ['users.id'], name=op.f('fk_club_banned_users_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_banned_users_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_banned_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', 'user_id', name=op.f('pk_club_banned_users'))
    )
    op.create_table('club_beauty_votes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=True),
    sa.Column('target_club_id', sa.BigInteger(), nullable=False),
    sa.Column('week_key', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_beauty_votes_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_club_id'], ['clubs.id'], name=op.f('fk_club_beauty_votes_target_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_beauty_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_beauty_votes')),
    sa.UniqueConstraint('user_id', 'week_key', name='uq_club_beauty_votes_user_week')
    )
    op.create_index('ix_club_beauty_votes_week', 'club_beauty_votes', ['week_key', 'target_club_id'], unique=False)
    op.create_table('club_day_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('norm_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('norm_target', sa.BigInteger(), server_default='3', nullable=False),
    sa.Column('contributors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('care_counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('streak', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('frozen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_day_stats_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_day_stats'))
    )
    op.create_index('uq_club_day_stat', 'club_day_stats', ['club_id', 'day'], unique=True)
    op.create_table('club_event_progress',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('ref', sa.String(length=32), nullable=False),
    sa.Column('week_key', sa.String(length=8), nullable=True),
    sa.Column('hp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('hp_max', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('score', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('state', sa.String(length=10), server_default='running', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_event_progress_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_event_progress'))
    )
    op.create_index('ix_club_event_progress_club', 'club_event_progress', ['club_id', sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_club_event_progress_kind', 'club_event_progress', ['kind', 'week_key'], unique=False)
    op.create_table('club_invites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('max_uses', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('uses', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_invites_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_club_invites_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_invites')),
    sa.UniqueConstraint('code', name=op.f('uq_club_invites_code'))
    )
    op.create_index(op.f('ix_club_invites_club_id'), 'club_invites', ['club_id'], unique=False)
    op.create_table('club_join_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=8), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_join_requests_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_club_join_requests_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_join_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_join_requests'))
    )
    op.create_index('ix_club_join_requests_club', 'club_join_requests', ['club_id', 'status'], unique=False)
    op.create_index(op.f('ix_club_join_requests_status'), 'club_join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_club_join_requests_user_id'), 'club_join_requests', ['user_id'], unique=False)
    op.create_table('club_lab_crafts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('mushroom_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_lab_crafts_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_lab_crafts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_lab_crafts'))
    )
    op.create_index(op.f('ix_club_lab_crafts_club_id'), 'club_lab_crafts', ['club_id'], unique=False)
    op.create_table('club_lab_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kombucha_id', sa.BigInteger(), nullable=False),
    sa.Column('stat', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_lab_runs_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kombucha_id'], ['kombuchas.id'], name=op.f('fk_club_lab_runs_kombucha_id_kombuchas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_lab_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_lab_runs'))
    )
    op.create_index('ix_club_lab_runs_club', 'club_lab_runs', ['club_id', 'ready_at'], unique=False)
    op.create_index(op.f('ix_club_lab_runs_user_id'), 'club_lab_runs', ['user_id'], unique=False)
    op.create_table('club_league_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('league_code', sa.String(length=12), nullable=False),
    sa.Column('week_key', sa.String(length=8), nullable=False),
    sa.Column('score', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('rank', sa.BigInteger(), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_league_memberships_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_code'], ['club_leagues.code'], name=op.f('fk_club_league_memberships_league_code_club_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_league_memberships'))
    )
    op.create_index('ix_club_league_board', 'club_league_memberships', ['league_code', 'week_key', sa.literal_column('score DESC')], unique=False)
    op.create_index('uq_club_league_week', 'club_league_memberships', ['club_id', 'week_key'], unique=True)
    op.create_table('club_members',
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=8), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contribution_week', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('contribution_total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('contrib_week_key', sa.String(length=8), nullable=True),
    sa.Column('last_contribution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_help_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warned_inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_members_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', 'user_id', name=op.f('pk_club_members'))
    )
    op.create_index('ix_club_members_user', 'club_members', ['user_id'], unique=False)
    op.create_table('club_membership_cooldowns',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_club_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_club_id'], ['clubs.id'], name=op.f('fk_club_membership_cooldowns_from_club_id_clubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_membership_cooldowns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_club_membership_cooldowns'))
    )
    op.create_table('club_museum',
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('tag', sa.String(length=5), nullable=False),
    sa.Column('emblem', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('color2', sa.String(length=9), nullable=False),
    sa.Column('stage', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('tank_xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('members_total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('scars', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('founded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbanded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_museum_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', name=op.f('pk_club_museum'))
    )
    op.create_table('club_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=8), server_default='auto', nullable=False),
    sa.Column('event', sa.String(length=24), nullable=True),
    sa.Column('body', sa.String(length=280), nullable=False),
    sa.Column('emoji', sa.String(length=16), server_default='📝', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_posts_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_club_posts_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_posts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_posts'))
    )
    op.create_index(op.f('ix_club_posts_created_at'), 'club_posts', ['created_at'], unique=False)
    op.create_index('ix_club_posts_feed', 'club_posts', ['club_id', sa.literal_column('id DESC')], unique=False)
    op.create_table('club_tank_mutations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.BigInteger(), nullable=False),
    sa.Column('crafted_by', sa.BigInteger(), nullable=True),
    sa.Column('crafted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_tank_mutations_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crafted_by'], ['users.id'], name=op.f('fk_club_tank_mutations_crafted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_tank_mutations')),
    sa.UniqueConstraint('club_id', 'stage', name='uq_club_tank_mutations_stage')
    )
    op.create_index(op.f('ix_club_tank_mutations_club_id'), 'club_tank_mutations', ['club_id'], unique=False)
    op.create_table('club_tanks',
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('best_xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sweet', sa.Double(), nullable=False),
    sa.Column('tea', sa.Double(), nullable=False),
    sa.Column('clean', sa.Double(), nullable=False),
    sa.Column('happy', sa.Double(), nullable=False),
    sa.Column('hp', sa.Double(), nullable=False),
    sa.Column('hp_max', sa.Double(), nullable=False),
    sa.Column('mold', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mold_cures', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('alive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('zero_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('died_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scars', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cooldowns', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('born_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_tanks_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', name=op.f('pk_club_tanks'))
    )
    op.create_table('club_wars',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('week_key', sa.String(length=8), nullable=False),
    sa.Column('league_code', sa.String(length=12), nullable=True),
    sa.Column('club_a_id', sa.BigInteger(), nullable=False),
    sa.Column('club_b_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=10), server_default='picking', nullable=False),
    sa.Column('picks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('score_a', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('score_b', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_a_id'], ['clubs.id'], name=op.f('fk_club_wars_club_a_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_b_id'], ['clubs.id'], name=op.f('fk_club_wars_club_b_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['clubs.id'], name=op.f('fk_club_wars_winner_id_clubs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_wars'))
    )
    op.create_index('ix_club_wars_club', 'club_wars', ['club_a_id', 'club_b_id'], unique=False)
    op.create_index('ix_club_wars_week', 'club_wars', ['week_key', 'league_code'], unique=False)
    op.create_table('club_reactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['club_posts.id'], name=op.f('fk_club_reactions_post_id_club_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_reactions')),
    sa.UniqueConstraint('post_id', 'user_id', 'emoji', name='uq_club_reactions_post_user_emoji')
    )
    op.create_index(op.f('ix_club_reactions_post_id'), 'club_reactions', ['post_id'], unique=False)
    op.create_table('club_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=8), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_reports_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_club_reports_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['club_posts.id'], name=op.f('fk_club_reports_post_id_club_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_reports'))
    )
    op.create_index(op.f('ix_club_reports_club_id'), 'club_reports', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_reports_status'), 'club_reports', ['status'], unique=False)
    # бизнес-войны: здоровье личного гриба и дебаф «Раненый»
    op.add_column('kombuchas', sa.Column('hp', sa.Float(), server_default='100', nullable=False))
    op.add_column('kombuchas', sa.Column('wounded_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kombuchas', 'wounded_until')
    op.drop_column('kombuchas', 'hp')
    op.drop_index(op.f('ix_club_reports_status'), table_name='club_reports')
    op.drop_index(op.f('ix_club_reports_club_id'), table_name='club_reports')
    op.drop_table('club_reports')
    op.drop_index(op.f('ix_club_reactions_post_id'), table_name='club_reactions')
    op.drop_table('club_reactions')
    op.drop_index('ix_club_wars_week', table_name='club_wars')
    op.drop_index('ix_club_wars_club', table_name='club_wars')
    op.drop_table('club_wars')
    op.drop_table('club_tanks')
    op.drop_index(op.f('ix_club_tank_mutations_club_id'), table_name='club_tank_mutations')
    op.drop_table('club_tank_mutations')
    op.drop_index('ix_club_posts_feed', table_name='club_posts')
    op.drop_index(op.f('ix_club_posts_created_at'), table_name='club_posts')
    op.drop_table('club_posts')
    op.drop_table('club_museum')
    op.drop_table('club_membership_cooldowns')
    op.drop_index('ix_club_members_user', table_name='club_members')
    op.drop_table('club_members')
    op.drop_index('uq_club_league_week', table_name='club_league_memberships')
    op.drop_index('ix_club_league_board', table_name='club_league_memberships')
    op.drop_table('club_league_memberships')
    op.drop_index(op.f('ix_club_lab_runs_user_id'), table_name='club_lab_runs')
    op.drop_index('ix_club_lab_runs_club', table_name='club_lab_runs')
    op.drop_table('club_lab_runs')
    op.drop_index(op.f('ix_club_lab_crafts_club_id'), table_name='club_lab_crafts')
    op.drop_table('club_lab_crafts')
    op.drop_index(op.f('ix_club_join_requests_user_id'), table_name='club_join_requests')
    op.drop_index(op.f('ix_club_join_requests_status'), table_name='club_join_requests')
    op.drop_index('ix_club_join_requests_club', table_name='club_join_requests')
    op.drop_table('club_join_requests')
    op.drop_index(op.f('ix_club_invites_club_id'), table_name='club_invites')
    op.drop_table('club_invites')
    op.drop_index('ix_club_event_progress_kind', table_name='club_event_progress')
    op.drop_index('ix_club_event_progress_club', table_name='club_event_progress')
    op.drop_table('club_event_progress')
    op.drop_index('uq_club_day_stat', table_name='club_day_stats')
    op.drop_table('club_day_stats')
    op.drop_index('ix_club_beauty_votes_week', table_name='club_beauty_votes')
    op.drop_table('club_beauty_votes')
    op.drop_table('club_banned_users')
    op.drop_index('uq_club_bank_tx_ref', table_name='club_bank_tx')
    op.drop_index('ix_club_bank_tx_club', table_name='club_bank_tx')
    op.drop_table('club_bank_tx')
    op.drop_index('uq_clubs_tag_lower', table_name='clubs')
    op.drop_index('uq_clubs_name_lower', table_name='clubs')
    op.drop_index(op.f('ix_clubs_status'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_leader_id'), table_name='clubs')
    op.drop_index('ix_clubs_active', table_name='clubs')
    op.drop_table('clubs')
    op.drop_table('club_leagues')
    # ### end Alembic commands ###
